<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="urn:SystemB" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="urn:SystemB"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:sch="http://www.example.org">
  <types>
    <xsd:schema targetNamespace="urn:SystemB/types" elementFormDefault="qualified">
      <xsd:import schemaLocation="SystemB.xsd" namespace="http://www.example.org"/>
    </xsd:schema>
  </types>
  <message name="saveSalesOrderRequest">
    <part name="request" element="sch:request"/>
  </message>
  <message name="saveSalesOrderResponse">
    <part name="response" element="sch:response"/>
  </message>
  <portType name="SystemB">
    <operation name="saveSalesOrder">
      <input message="tns:saveSalesOrderRequest"/>
      <output message="tns:saveSalesOrderResponse"/>
    </operation>
  </portType>
  <binding name="SystemBSOAP11Binding" type="tns:SystemB">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="saveSalesOrder">
      <soap:operation style="document" soapAction="urn:SystemB/saveSalesOrder"/>
      <input>
        <soap:body use="literal" parts="request"/>
      </input>
      <output>
        <soap:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
  <service name="SystemB">
    <port name="SystemBPort" binding="tns:SystemBSOAP11Binding">
      <soap:address location="http://www.example.com"/>
    </port>
  </service>
</definitions>