<wsdl:definitions
     name="dbSystemB"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DbAdapterPocApp/Integration/dbSystemB"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DbAdapterPocApp/Integration/dbSystemB"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbSystemB"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="dbSystemB_plt" >
    <plt:role name="dbSystemB_role" >
      <plt:portType name="tns:dbSystemB_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbSystemB" schemaLocation="../Schemas/dbSystemB_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="SalesOrderCollection_msg">
        <wsdl:part name="SalesOrderCollection" element="top:SalesOrderCollection"/>
    </wsdl:message>
    <wsdl:portType name="dbSystemB_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:SalesOrderCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
