<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="SystemBMediator"
     targetNamespace="http://xmlns.oracle.com/DbAdapterPocApp/Integration/SystemBMediator"
     xmlns:tns="http://xmlns.oracle.com/DbAdapterPocApp/Integration/SystemBMediator"
     xmlns:inp1="http://www.integration.org/sales"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.integration.org/sales" schemaLocation="../Schemas/sales.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="request" element="inp1:order"/>
    </wsdl:message>
    <wsdl:portType name="execute_ptt">
        <wsdl:operation name="execute">
            <wsdl:input message="tns:requestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
