CREATE TABLE SYSTEM_A.SALES_ORDER 
(
  ID NUMBER(10) NOT NULL 
, CUSTOMER VARCHAR2(100) NOT NULL 
, PRICE NUMBER(8,2) NOT NULL 
, STATUS VARCHAR2(100) NOT NULL 
, CONSTRAINT SALES_ORDER_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER USER SYSTEM_A IDENTIFIED BY welcome1;

GRANT CONNECT, RESOURCE TO SYSTEM_A;