
package systemb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import org.example.ObjectFactory;
import org.example.Request;
import org.example.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebService(name = "SystemB", targetNamespace = "urn:SystemB")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface SystemB {


    /**
     *
     * @param request
     * @return
     *     returns org.example.Response
     */
    @WebMethod(action = "urn:SystemB/saveSalesOrder")
    @WebResult(name = "response", targetNamespace = "http://www.example.org", partName = "response")
    public Response saveSalesOrder(@WebParam(name = "request", targetNamespace = "http://www.example.org",
                                             partName = "request") Request request);

}
